export enum ROUTES {
  ABOUT = "/about",
  HOME = "/",
  PROJECTS = "/projects",
  EXPERIENCE = "/jobs",
  CONTACT = "/contact",
  FEEDBACK = "/feedback",
  SIGN_IN = "/sign-in",
  LOGIN = "/login",
  EDUCATION = "/education",
  UPDATE_ABOUT = "/update-about",
  UPDATE_PROJECTS = "/update-projects",
  UPDATE_EXPERIENCE = "/update-jobs",
  UPDATE_CONTACT = "/update-contact",
  UPDATE_FEEDBACK = "/update-feedback",
  UPDATE_EDUCATION = "/update-education",
  CREATE_JOB = "/create-job",
  ADD_SOFTWARE = "/add-software",
  ADD_PROJECT = "/add-project",
  ADD_EDUCATION = "/add-education",
  ADD_FEEDBACK = "/add-feedback",
}
